# Generated by Django 5.0.1 on 2024-01-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryproduct',
            unique_together={('category', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'price')},
        ),
    ]
