# Generated by Django 5.0.1 on 2024-01-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categoryproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
